// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type ConvertRequest struct {
	LongUrl string `json:"longurl" validate:"required"`
}

type ConvertResponse struct {
	ShortUrl string `json:"shorturl"`
}

type ShowRequest struct {
	ShortUrl string `path:"shorturl"  validate:"required"`
}

type ShowResponse struct {
	LongUrl string `json:"longurl"`
}
